# Generated by Django 4.1.4 on 2023-01-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField(max_length=50)),
                ('producto', models.CharField(max_length=60)),
                ('descricorta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(max_length=20)),
                ('valorcom', models.IntegerField(max_length=60)),
            ],
        ),
    ]
